# Generated by Django 4.0.5 on 2022-06-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='Asset',
        ),
    ]
