# Generated by Django 4.0.5 on 2022-06-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_rename_title_article_asset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Asset',
        ),
    ]
